# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
    - solaris
  goarch:
    - amd64
    - 386

archives:
- replacements:
    darwin: macos
    386: x86
    amd64: x64
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - tldr-pages-LICENSE.md

brews:
- github:
    owner: eiladin
    name: homebrew-tldr
  commit_author:
    name: Sami Khan
    email: eiladin@gmail.com
  folder: Formula
  description: "Simplified and community-driven man pages"
  test: |
    system "#{bin}/tldr -version"
  install: |
    bin.install "tldr"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
