name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Run test
      uses: goreleaser/goreleaser-action@v2.1.1
      with:
        version: latest
        args: release --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.INTEGRATION_TOKEN }}
